### ISSUE TITLE
No smooth scroll in Visual modes

### ISSUE THREAD

**Issue by anihm136** [psliwka/vim-smoothie#12]
When a visual selection is active, the smooth scroll action does not work

**Comment by psliwka** [comment]
This is a valid issue indeed. Not sure how to fix this yet, but I'll be glad to review a PR.

**Comment by subnut** [comment]
@anihm136 @zhixuan-lin @karb94 @WhyNotHugo @jaredramirez @mitchellwrosen @nomasprime @Melkster

Try #21 
Make sure `:echo has('nvim') || has('patch-8.2.1280')` returns `1`

**Comment by anihm136** [comment]
@subnut This works perfectly for me! The other changes in the PR are also helpful. Thanks!

**Comment by WhyNotHugo** [comment]
@subnut it returns `1` for me.

**Comment by subnut** [comment]
> @subnut it returns 1 for me.

Then vim-smoothie should automatically work in Visual mode too. Does it not?
