### ISSUE TITLE
Add ^D ^U ^F ^B to the jump list (optionally) 

### ISSUE THREAD

**Issue by voyeg3r** [psliwka/vim-smoothie#14]
It would be great to add ^D ^U ^F ^B to the jump list or at least allow to, like:
let g:smoothie_add_jumplist = 1

**Comment by voyeg3r** [comment]
I have discovered how to add any place to the jump list:

    `call setpos("''", getpos("."))`

**Comment by psliwka** [comment]
Sorry, I'm reluctant to add this since native Vim scrolling commands don't alter the jumplist. I encourage you to implement this via custom mappings instead.
