### ISSUE TITLE
Doesn't scroll over wrapped lines after activating Goyo

### ISSUE THREAD

**Issue by alexmozaidze** [psliwka/vim-smoothie#16]
Whenever I activate [Goyo](https://github.com/junegunn/goyo.vim) I cannot seem to scroll over soft-wrapped lines. I can solve it by deactivating soft-wrapping but it just looks ugly if I do.

**Comment by psliwka** [comment]
I'm not using Goyo so I can't really debug this :( Help wanted!

**Comment by alexmozaidze** [comment]
It seems like the problem occurs not just with Goyo but with splits in general. Whenever I open a split (horizontal or vertical, doesn't seem to matter) the problem is recreated, I can't scroll over the soft-wrapped lines. I've noted that in order to fix the issue I need to make my terminal screen wide enough so that no lines are wrapped and then back to normal, but it doesn't seem like an optimal solution. (at least for me)

**Comment by alexmozaidze** [comment]
It seems that the problem was in using <C-U> and <C-D> as motions in `step_up()` and `step_down()` functions, so I've changed those motions with j<C-e> and k<C-y>.
