### ISSUE TITLE
Extremely slow in firenvim

### ISSUE THREAD

**Issue by xerus2000** [psliwka/vim-smoothie#17]
I use [firenvim](https://github.com/glacambre/firenvim), and oh my, the smooth scrolling is incredibly slow in there. I am now looking for a way to disable this plugin in all firenvim instances.

Reporting this here in case this can be fixed, or maybe disabled in firenvim by default, if others have the same issue.

**Comment by xerus2000** [comment]
Use this to disable it:
```vim
if exists('g:started_by_firenvim')
	let g:smoothie_no_default_mappings=1 "extremely slow, see https://github.com/psliwka/vim-smoothie/issues/17
endif
```

**Comment by glacambre** [comment]
Hi, this is most probably a Firenvim issue - it'll be fixed once https://github.com/glacambre/firenvim/issues/347 is fixed :)

**Comment by psliwka** [comment]
Thank you for your input. Since the problem affects more UIs than just Firenvim (f.ex. slow SSH sessions), I've created #19 for possible generic improvements. #17 will stay dedicated to Firenvim-specific fixes/workarounds.

**Comment by subnut** [comment]
@xerus2000 I have tried to implement the _minmal_ solution @psliwka talked in his post above
Please test #21 using the following config -
```vim
let g:smoothie_disabled = 1
```
and report bugs, if any

**Comment by psliwka** [comment]
Note to myself: check whether https://github.com/glacambre/firenvim/issues/347 is fixed in a couple of months. If not (or the smooth scrolling is slow with it anyway), teach vim-smoothie to auto-disable itself if `g:started_by_firenvim` is set.

**Comment by glacambre** [comment]
@psliwka #347 has been fixed :)

**Comment by psliwka** [comment]
Awesome, thanks for update @glacambre!

@xerus2000: could you please re-test how does your firenvim+vim-smoothie setup perform with the new renderer?

**Comment by xerus2000** [comment]
Works great, thanks for collaborating on this :)
