### ISSUE TITLE
Support for mapping of ctrl+f etc.

### ISSUE THREAD

**Issue by BStephenBB** [psliwka/vim-smoothie#24]
Is there a way to map something to ctrl+f (and all the other scroll commands) so that it still smooth scrolls?

Currently if I manually input `ctrl+f` (or any other scroll motion) I get the smooth scrolling behavior, but when I try to add some mappings, ie:
```
 " use leader d to scroll down a page
nnoremap <leader>d <C-F>
 " use leader u to scroll up a page
nnoremap <leader>u <C-B>
```
I no longer get smooth scrolling when using my mapping.

**Comment by subnut** [comment]
Use `nmap` instead of `nnoremap`

Please close the issue.

**Comment by BStephenBB** [comment]
Ah, right 🤦  Thanks!
