### ISSUE TITLE
Ctrl-d not working

### ISSUE THREAD

**Issue by timonson** [psliwka/vim-smoothie#25]
Thank you for this amazing plugin!

All key combinations work with the exception of `Ctrl-d`. When pressing `Ctrl-d` the cursor jumps immediately to the right position but without *smooth* scrolling.

I checked `:nnoremap <C-d>` which says *no mapping*.

Could you maybe give me a recommendation on how to debug this? Thank you!

System: arch
Vim: 8.2

**Comment by timonson** [comment]
I found the issue. I have `vnoremap <C-d> "+d<ESC>` in my vimrc. I did not expect this mapping to influence the behavior in non-visual mode. Is this an expected behavior?

**Comment by psliwka** [comment]
Could not reproduce – `vnoremap <C-d> "+d<ESC>` does not break smooth ^D in normal mode for me. Tested with NVIM v0.4.4.

**Comment by timonson** [comment]
Well, it is happening in vim. Not sure why you closed this issue. Is this plugin exclusively for nvim?

**Comment by psliwka** [comment]
I tested it under VIM 8.2 (patches 1-2500) too, and I couldn't reproduce it either. I closed the ticket because there is nothing more we can do to proceed here I'm afraid. However, feel more than welcome to post additional details if you think we can resurrect it ;)
