### ISSUE TITLE
Handle `zz` and similar commands

### ISSUE THREAD

**Issue by psliwka** [psliwka/vim-smoothie#26]
This is continuation of https://github.com/psliwka/vim-smoothie/issues/11#issuecomment-609037304

> In another issue you mention that smoothie only works with commands that move the window over the buffer but not by moving the cursor. Does this apply to zz, zt and zb as well?

`zz` and friends are scrolling commands indeed, and should be quite easy to implement. I'd be glad to review a PR adding them ;)

**Comment by subnut** [comment]
But vim-smoothie _does_ change the cursor position if `:set startofline`

**Comment by psliwka** [comment]
Implemented in f2aaab110b49da21ab7abf4858173e3194109f6a.

**Comment by WhyNotHugo** [comment]
Lovely! Thanks!
