### ISSUE TITLE
New easing curve too slow to stop

### ISSUE THREAD

**Issue by oblitum** [psliwka/vim-smoothie#27]
Hi, not sure whether it fits feature request or bug, but for me, the new animation is a bit slow at the end to stop. Could it be made so that by default there's a nice easing curve but not so slow motion at the end?

**Comment by blmatthews** [comment]
I agree, I much preferred the version I had before I updated a few days ago (unfortunately I don't know what that was). I've been using the latest version for a few days and so far can't get used to it, as soon as it starts slowing I think it's done and start doing things, which then get done to the wrong text when it scrolls a few more lines.

**Comment by psliwka** [comment]
Oh, hi @oblitum! Nice to see `caps2esc` author here ;)

Thanks for bisecting this, @blmatthews. I'm surprised you had to set `g:smoothie_speed_exponentiation_factor` to 1.1. Setting this to just 1.0 should be enough to cancel out recent changes to the deceleration curve. There was, however, one more bug fixed recently, which actually caused the cursor to speed up a little just before reaching its target position. I am wondering whether this could be desired behavior in your eyes. Could you please compare how does 0c1696a9b3b8db8cdb567a5fe8b9d6d27e118c0b and 6cd5dea1698c0238a6d08eb8fc66696007483640 work for you?

**Comment by psliwka** [comment]
^ Reopening due to being closed mistakenly with a poorly-worded commit message.

**Comment by psliwka** [comment]
I've identified a potential bug in Vim's timer handling which could have caused this, and pushed a fix for it in f2aaab110b49da21ab7abf4858173e3194109f6a. @oblitum, @blmatthews, could you please re-test if this fixes the issue for you?

**Comment by psliwka** [comment]
Marking as resolved. Feel free to open another issue in case the problem persists.
