### ISSUE TITLE
Scrolling doesn't work for control + f / control +b

### ISSUE THREAD

**Issue by AndreKucharzyk** [psliwka/vim-smoothie#32]
Hi Piotr, 

smooth scrolling works correctly for control + u / control + d, but for control + f / control +b there is no smoothness ◔‿◔

NVIM v0.5.1
Terminal 2.11

**Comment by ethan-enhe** [comment]
> Hi Piotr,
> 
> smooth scrolling works correctly for control + u / control + d, but for control + f / control +b there is no smoothness ◔‿◔
> 
> NVIM v0.5.1 Terminal 2.11

Did you use any plugins which remapped <c-f>(like coc.nvim)? I solve it by removing a part in my cofiguration which remap <C-f> and <C-b> for scroll float windows/popups.

**Comment by psliwka** [comment]
As @ethan-enhe, it's most likely a conflict with other plugin. Marking as closed.
