### ISSUE TITLE
Non-backwards-compatible updates

### ISSUE THREAD

**Issue by ds2606** [psliwka/vim-smoothie#35]
Vim-plugged just updated my local `vim-smoothie` codebase, and my scrolling keybindings seem to have broken.

I had these bindings:
```vim
noremap <silent> - :call smoothie#downwards()<CR>
noremap <silent> = :call smoothie#upwards()<CR>
```
They now do not work, so I tried updating them to 

```vim
noremap <silent> - :call smoothie#do("<C-U>")<CR>
noremap <silent> = :call smoothie#do("<C-D">)<CR>
```
As per the `README`, but they still do not cause scrolling. (There could be a lot of reasons, one of which could be that `coc.nvim` also binds `C-D` / `C-U` and vim-smoothie's bindings are recursive onto those).

Side note: the README has duplicate lines here:
```vim
nnoremap <unique> <C-D> <cmd>call smoothie#do("<C-D>") <CR>
vnoremap <unique> <C-D> <cmd>call smoothie#do("<C-D>") <CR>
```

**Comment by psliwka** [comment]
Thanks for reporting this, @ds2606. I just pushed a fix, after which your original bindings should keep working. Also, I updated the README to show correctly how to add custom bindings using the new API.

> Side note: the README has duplicate lines here:

They're not duplicate ;) The first one adds normal mode mapping (`nnoremap`), the second one is for visual mode (`vnoremap`). Unfortunately, AFAIK Vim does not allow to map both at once.

**Comment by ds2606** [comment]
Thanks @psilwka! And haha sorry I should know better than to miss the `v`/`n` difference..

Unfortunately, the scrolling behavior is much choppier on fc7f0b3 than the last good commit I've identified, which for now is 10fd0. I'm not sure why this is, but  for now I think I'll need to leave `HEAD` there
