### ISSUE TITLE
Cursor loses the column position when scrolling

### ISSUE THREAD

**Issue by JS-Zheng** [psliwka/vim-smoothie#39]
vim-smoothie version: b440f13
vim version: 8.2.4700

As mentioned in the title, the cursor moves to the head of line instead of the original column position when scrolling. I think it should keep the same column position, or provides a config option to control cursor-position behavior.

**Comment by psliwka** [comment]
There is already such option, see `:help 'startofline'` ;)

**Comment by JS-Zheng** [comment]
I know, my `sol` setting is `off`
This issue still exists, the cursor is **not** kept in the same column (if possible).

**Comment by psliwka** [comment]
Ah, sorry, there was indeed a bug breaking `startofline` handling. Should be fixed now, thanks!
