### ISSUE TITLE
Disable default mappings

### ISSUE THREAD

**Issue by pwntester** [psliwka/vim-smoothie#4]
Please provide an option to disable default mappings. They may overlap with user mappings (eg: I use <C-f> for Defx) 

Thanks

**Comment by null-sleep** [comment]
+1 I had to manually comment out <C-f> from smoothie.vim to be able to use it

**Comment by psliwka** [comment]
Say hello to [g:smoothie_no_default_mappings](https://github.com/psliwka/vim-smoothie#customization)!
