### ISSUE TITLE
native vim plugin system

### ISSUE THREAD

**Issue by lukR5** [psliwka/vim-smoothie#48]
Hi.

I love vim, and vim-smoothie is great plugin! Recently I switch to the native-vim plugin system, and I have real trouble to run vim-smoothie that way :/
Any thoughts?

EDIT:
So vim-smoothie work perfectly ok. The issue was with `set scrolloff=10` command...

**Comment by psliwka** [comment]
> So vim-smoothie work perfectly ok. 

Marking this issue as resolved then. Feel free to contribute additional installation instructions to the README though ;)
