### ISSUE TITLE
Flickering when Tagbar Opened SImulataneously

### ISSUE THREAD

**Issue by neerajbadlani** [psliwka/vim-smoothie#6]
While Reading Code , when Tagbar is opened in same view , there is quite a noticable flickering .

**Comment by psliwka** [comment]
Not using tagbar or ctags so I can't really test it, but in general having multiple windows open can prevent vim from doing certain terminal redraw optimizations, which may cause flickering.

@neerajbadlani, can you pinpoint the problem to any particular terminal emulator? Can you check if the problem persists when using GPU accelerated terminal such as https://github.com/kovidgoyal/kitty , or GUI such as gVim?
