### ISSUE TITLE
Cursor Lands on Different Starting Point

### ISSUE THREAD

**Issue by neerajbadlani** [psliwka/vim-smoothie#7]
Lets say when i Start downwards movement , my cursor on line was at column=0 , when finally movement finishes , it lands at first character on the line which might be at column 8 ( in code indentations ) , and the cursor during travelling touches first character of each line , which in code files is quite irritating .

**Comment by psliwka** [comment]
This is sort of expected if you have `startofline` enabled (on by default):

```
'startofline' 'sol'	boolean	(default on)
			global
	When "on" the commands listed below move the cursor to the first
	non-blank of the line.  When off the cursor is kept in the same column
	(if possible).  This applies to the commands: CTRL-D, CTRL-U, CTRL-B,
	CTRL-F, [...]

```

Does `:set nostartofline` solve your issue, @neerajbadlani? If not, feel free to post additional comments here!
