### ISSUE TITLE
Set different scroll speed for Mouse Wheel scrolling

### ISSUE THREAD

**Issue by bytesizedpcs** [psliwka/vim-smoothie#8]
It would be cool to be able to set a different scroll speed based on what type of input you're using.

Currently mouse wheel scrolling is way too fast, but changing the base speed makes it too slow for mapped keybinds.

**Comment by psliwka** [comment]
This is weird. This plugin is not supposed to alter mouse scrolling in any way at this point. Could you please post more details, @bytesizedpcs?

**Comment by bytesizedpcs** [comment]
Sorry, after inspecting my vim settings this issue seemed to stem from overlapping scroll plugins.
